name: cargo-cache

inputs:
  target:
    required: true
  scope:
    required: true

runs:
  using: composite
  steps:
    - name: cache dependencies
      uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ inputs.target }}-cargo-deps-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ inputs.target }}-cargo-deps-

    - name: cache build
      uses: actions/cache@v6
      with:
        path: target/
        key: ${{ inputs.target }}-cargo-build-${{ inputs.scope }}-${{ hashFiles('**/Cargo.lock') }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.target }}-cargo-build-${{ inputs.scope }}-${{ hashFiles('**/Cargo.lock') }}-
          ${{ inputs.target }}-cargo-build-${{ inputs.scope }}-
