name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  fmt:
    uses: ./.github/workflows/_fmt.yaml

  msrv:
    uses: ./.github/workflows/_msrv.yaml

  clippy:
    uses: ./.github/workflows/_clippy.yaml

  test:
    uses: ./.github/workflows/_test.yaml

  docs:
    uses: ./.github/workflows/_doc.yaml

  deny:
    uses: ./.github/workflows/_deny.yaml
